version: '3'
services:
  spring:
    image: 'aeroporto:0.0.1-SNAPSHOT'
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    networks:
      - postgres-network
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - './.mongodb:/data/db'
    ports:
      - '27017:27017'
    restart: unless-stopped
networks:
  postgres-network:
    driver: bridge
